server:
  port: 9999

spring:
  application:
    name: ServiceProvider
  cloud:
    zookeeper:
      discovery:
        connectString: localhost:2181
        enabled: true

logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN
