logging:
  level:
    ROOT: DEBUG

spring:
  application:
    name: SpringCloudStreamProducer
  cloud:
    stream:
      bindings:
        eventSupplier-out-0:
          destination: person-command
        randomMessage-out-0:
          destination: random-message
        sink1-in-0:
          destination: random-message
      function:
        definition: eventSupplier;randomMessage;sink1
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
server:
  port: 8085