logging:
  level:
    ROOT: DEBUG

spring:
  application:
    name: SpringCloudStreamProducer
  cloud:
#    function:
#      definition: eventSupplier;randomMessage
    stream:
      bindings:
        eventSupplier-out-0:
          destination: person-command
        randomMessage-out-0:
          destination: random-message-0
        process-out-0:
          destination: person-event
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
server:
  port: 8085