create table if not exists reviews_0
(
    id               integer generated by default as identity
    constraint pk_reviews_0
    primary key,
    text             varchar(3000),
    author           varchar(255),
    author_telephone varchar(255),
    author_email     varchar(255),
    invoice_code     varchar(255),
    created_at       timestamp,
    last_modified_at timestamp,
    course_id        integer
    );

create table if not exists reviews_1
(
    id               integer generated by default as identity
    constraint pk_reviews_1
    primary key,
    text             varchar(3000),
    author           varchar(255),
    author_telephone varchar(255),
    author_email     varchar(255),
    invoice_code     varchar(255),
    created_at       timestamp,
    last_modified_at timestamp,
    course_id        integer
    );