#logging:
#  level:
#    ROOT: DEBUG

spring:
  application:
    name: SpringAroConsumer
  cloud:
    stream:
      bindings:
        process-in-0:
          destination: person-event
          group: person-event
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
          configuration:
            auto:
              offset:
                reset: earliest
server:
  port: 8086