spring:
  application:
    name: account-service

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
#    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}} // don't do this in prod!
